save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  provider: "$.message.order.provider"
  items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  payments: "$.message.order.payments[*]"
  tags: "$.message.order.tags[*]"
  billing: "$.message.order.billing"

