save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  timestamp: "$.context.timestamp"
  order_id: "$.message.order_id"
  cancellation_reason_id: "$.message.cancellation_reason_id"
