save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  bap_id: "$.context.bap_id"
  bpp_id: "$.context.bpp_id"
  timestamp: "$.context.timestamp"
  provider: "$.message.order.provider"
  items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  quote: "$.message.order.quote"
  quote_breakup: "$.message.order.quote.breakup[*]"
  payments: "$.message.order.payments[*]"
  offers: "$.message.order.offers[*]"
