save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  bap_id: "$.context.bap_id"
  bap_uri: "$.context.bap_uri"
  timestamp: "$.context.timestamp"
  domain: "$.context.domain"
  version: "$.context.version"
  location: "$.context.location"
  collected_by: "$.message.intent.payment.collected_by"
  tags: "$.message.intent.tags"
  bff_tags: "$.message.intent.payment.tags"
  start_time: "$.message.intent.fulfillment.stops[?(@.type=='START')].time.range.start"
  end_time: "$.message.intent.fulfillment.stops[?(@.type=='START')].time.range.end"
  city_code: "$.context.location.city.code"
  vehicle_category: "$.message.intent.fulfillment.vehicle.category"
