save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  bap_id: "$.context.bap_id"
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri"
  timestamp: "$.context.timestamp"
  order: "$.message.order"
  items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  provider: "$.message.order.provider"
  offers: "$.message.order.offers[*]"
