save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  timestamp: "$.context.timestamp"
  bap_id: "$.context.bap_id"
  bap_uri: "$.context.bap_uri"
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri"
