save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  timestamp: "$.context.timestamp"
  update_target: "$.message.update_target"
  order_id: "$.message.order.id"
  items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
