save-data:
  cancellation_reason_id: $.message.cancellation_reason_id
  message_id: $.context.message_id
  is_cancel_called: $.context.action
  order_id: $.message.order_id
  transaction_id: $.context.transaction_id
  bap_id: $.context.bap_id
  bap_uri: $.context.bap_uri
  bpp_id: $.context.bpp_id
  bpp_uri: $.context.bpp_uri
  timestamp: $.context.timestamp
  domain: $.context.domain
  version: $.context.version
  city: $.context.city
  action: $.context.action
