save-data:
  fulfillments: $.message.order.fulfillments[*]
  billing: $.message.order.billing
  message_id: $.context.message_id
  items: $.message.order.items[*]
  payment: $.message.order.payment
  insurance_required: $.message.order.fulfillments[*].tags[?(@.code=="special_req")].list[?(@.code=="insurance_required")].value
  insurance_owner: $.message.order.fulfillments[*].tags[?(@.code=="special_req")].list[?(@.code=="insurance_owner")].value
  transaction_id: $.context.transaction_id
  bap_id: $.context.bap_id
  bap_uri: $.context.bap_uri
  bpp_id: $.context.bpp_id
  bpp_uri: $.context.bpp_uri
  timestamp: $.context.timestamp
  domain: $.context.domain
  version: $.context.version
  city: $.context.city
  action: $.context.action
  provider_id: $.message.order.provider.id
  item_id: $.message.order.items[0].id
  fulfillment_id: $.message.order.fulfillments[0].id
