save-data:
  order_id: $.message.order.id
  order_status: $.message.order.state
  message_id: $.context.message_id
  confirm_create_at_timestamp: $.message.order.created_at
  tat: $.message.order.items[0].time.duration
  fulfillments: $.message.order.fulfillments[*]
  confirm_fulfillments: $.message.order.fulfillments[*]
  items: $.message.order.items[*]
  quote: $.message.order.quote
  payment: $.message.order.payment
  linked_order: $.message.order["@ondc/org/linked_order"]
  rto_action: $.message.order.fulfillments[*].tags[?(@.code=="rto_action")].list[?(@.code=="return_to_origin")].value
  rto_verification_code: $.message.order.fulfillments[*].tags[?(@.code=="rto_verification")].list[?(@.code=="short_desc")].value
  confirm_tags: $.message.order.tags
  b2b_payments: $.message.order.payments
  transaction_id: $.context.transaction_id
  bap_id: $.context.bap_id
  bap_uri: $.context.bap_uri
  bpp_id: $.context.bpp_id
  bpp_uri: $.context.bpp_uri
  timestamp: $.context.timestamp
  domain: $.context.domain
  version: $.context.version
  city: $.context.city
  action: $.context.action
  provider_id: $.message.order.provider.id
  item_id: $.message.order.items[0].id
  fulfillment_id: $.message.order.fulfillments[0].id
